## 5. 텐서플로로 선형 회귀 구현하기

In [1]:
import tensorflow as tf
print(f'TensorFlow version: {tf.__version__}')
tf.random.set_seed(1)

2025-11-28 13:50:39.433581: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-11-28 13:50:39.508154: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI AVX_VNNI_INT8 AVX_NE_CONVERT FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-11-28 13:50:41.130453: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


TensorFlow version: 2.20.0


In [2]:
x_train = tf.constant([[1.], [2.], [3.]], dtype=tf.float32)
y_train = tf.constant([[2.], [4.], [6.]], dtype=tf.float32)
print(x_train)
print(x_train.shape)
print(y_train)
print(y_train.shape)

tf.Tensor(
[[1.]
 [2.]
 [3.]], shape=(3, 1), dtype=float32)
(3, 1)
tf.Tensor(
[[2.]
 [4.]
 [6.]], shape=(3, 1), dtype=float32)
(3, 1)


2025-11-28 13:50:42.519002: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [3]:
# 가중치 W와 편향 b를 0으로 초기화
W = tf.Variable(tf.zeros([1, 1]))
b = tf.Variable(tf.zeros([1]))
hypothesis = x_train * W + b
print(hypothesis)
cost = tf.reduce_mean(tf.square(hypothesis - y_train))
print(cost.numpy())

tf.Tensor(
[[0.]
 [0.]
 [0.]], shape=(3, 1), dtype=float32)
18.666666


In [4]:
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)
with tf.GradientTape() as tape:
    hypothesis = x_train * W + b
    cost = tf.reduce_mean(tf.square(hypothesis - y_train))
grads = tape.gradient(cost, [W, b])
optimizer.apply_gradients(zip(grads, [W, b]))
print(f'After one step -> W: {W.numpy()}, b: {b.numpy()}, cost: {cost.numpy()}')

After one step -> W: [[0.18666668]], b: [0.08], cost: 18.66666603088379


In [5]:
W = tf.Variable(tf.zeros([1, 1]))
b = tf.Variable(tf.zeros([1]))
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)
nb_epochs = 5000
for epoch in range(nb_epochs + 1):
    with tf.GradientTape() as tape:
        hypothesis = x_train * W + b
        cost = tf.reduce_mean(tf.square(hypothesis - y_train))
    grads = tape.gradient(cost, [W, b])
    optimizer.apply_gradients(zip(grads, [W, b]))
    if epoch % 100 == 0:
        print(f'Epoch {epoch:4d}/{nb_epochs} W: {W.numpy().item():.3f}, b: {b.numpy().item():.3f} Cost: {cost.numpy():.6f}')

Epoch    0/5000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/5000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/5000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/5000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/5000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/5000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/5000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/5000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/5000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/5000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/5000 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/5000 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/5000 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/5000 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/5000 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/5000 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/5000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/5000 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/5000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/5000 W: 1.997, b: 0.008 Cost: 0.000008

## 7. 자동 미분(Autograd) 실습하기

In [6]:
w = tf.Variable(2.0)
with tf.GradientTape() as tape:
    z = 2 * w ** 2 + 5
grad = tape.gradient(z, w)
print('수식을 w로 미분한 값 : {}'.format(grad.numpy()))

수식을 w로 미분한 값 : 8.0
